# Generated by Django 2.2.1 on 2020-07-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example2',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
