# Generated by Django 2.2.1 on 2020-07-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Example2', '0002_auto_20200701_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example2',
            name='edad',
        ),
    ]
