# Generated by Django 2.2.1 on 2020-07-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example1',
            name='name',
        ),
    ]
